//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoranalysis
    {
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Auditor { get; set; }
        public int Cost { get; set; }
        public int ConstForClient { get; set; }
        public int Salary { get; set; }
        public string Factory { get; set; }
    }
}
