//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientcontacts
    {
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string PatrName { get; set; }
        public string Position { get; set; }
        public string Birth { get; set; }
        public string Telephone { get; set; }
        public string Mail { get; set; }
        public string Comments { get; set; }
        public bool Vip { get; set; }
        public string ClientID { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
