//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.clientcontacts = new HashSet<clientcontacts>();
        }
    
        public string ID { get; set; }
        public string Company { get; set; }
        public string Activity { get; set; }
        public string Idx { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Office { get; set; }
        public string AddrComments { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Own { get; set; }
        public string Auditor { get; set; }
        public string Works { get; set; }
        public string Establishing { get; set; }
        public bool Special { get; set; }
    
        public virtual ICollection<clientcontacts> clientcontacts { get; set; }
    }
}
