//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyanalysis
    {
        public string Id { get; set; }
        public string Company { get; set; }
        public int Income { get; set; }
        public int Costs { get; set; }
        public int Result { get; set; }
        public System.DateTime Date { get; set; }
    }
}
