//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSP.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PspEntities : DbContext
    {
        public PspEntities()
            : base("name=pspEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<auditoranalysis> auditoranalysis { get; set; }
        public DbSet<baseusers> baseusers { get; set; }
        public DbSet<clientcontacts> clientcontacts { get; set; }
        public DbSet<clients> clients { get; set; }
        public DbSet<companyanalysis> companyanalysis { get; set; }
        public DbSet<events> events { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<history> history { get; set; }
        public DbSet<mails> mails { get; set; }
        public DbSet<users> users { get; set; }
    }
}
