//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PSP.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            ID = Guid.NewGuid().ToString();
            this.events = new HashSet<events>();
        }
    
        public string ID { get; set; }
        [Required]
        [Display(Name = "Имя")]
        public string Name { get; set; }
        
        [Display(Name = "Контакты")]
        public string Contact { get; set; }
        public string GroupID { get; set; }
        public sbyte Hidden { get; set; }

        [Display(Name = "Группа")]
        public virtual groups groups { get; set; }
        public virtual ICollection<events> events { get; set; }
    }
}
